name: Update app version on release
on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update .app_version with release tag
        run: |
          echo "v${{ github.event.release.tag_name }}" > .app_version
          git add .app_version

      - name: Commit version update
        run: |
          git commit -m "Bump .app_version to ${{ github.event.release.tag_name }}"

      - name: Push changes to main
        run: |
          git push origin main

      - name: Checkout production branch
        run: |
          git fetch origin
          git checkout production

      - name: Merge main into production
        run: |
          git rebase main

      - name: Push changes to production
        run: |
          git push origin production
