name: Test Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy (e.g., staging, uat, feature-branch)'
        default: 'staging'
        required: true
      environment:
        description: 'Select the environment to deploy'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - uat
  push:
    branches:
      - test-workflow-dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        env:
          BRANCH: ${{ inputs.branch }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "Branch: $BRANCH"
          echo "Environment: $ENVIRONMENT"
